-- Estatísticas dos passeios virtuais 360°.
-- Registra somente eventos anônimos. Nenhum IP ou dado pessoal é armazenado.

create table if not exists public.virtual_tour_analytics_events (
  id bigint generated by default as identity primary key,
  tour_id uuid not null references public.virtual_tours(id) on delete cascade,
  scene_id uuid references public.virtual_tour_scenes(id) on delete set null,
  event_type text not null,
  visitor_session_id uuid not null,
  is_embedded boolean not null default false,
  created_at timestamptz not null default now(),
  constraint virtual_tour_analytics_event_type_check
    check (event_type in ('tour_view', 'scene_view', 'whatsapp_click')),
  constraint virtual_tour_analytics_scene_check
    check (
      (event_type = 'scene_view' and scene_id is not null)
      or
      (event_type <> 'scene_view' and scene_id is null)
    )
);

create index if not exists virtual_tour_analytics_tour_created_idx
  on public.virtual_tour_analytics_events (tour_id, created_at desc);

create index if not exists virtual_tour_analytics_tour_type_created_idx
  on public.virtual_tour_analytics_events (tour_id, event_type, created_at desc);

create index if not exists virtual_tour_analytics_scene_created_idx
  on public.virtual_tour_analytics_events (scene_id, created_at desc)
  where scene_id is not null;

alter table public.virtual_tour_analytics_events enable row level security;

drop policy if exists "Management admins read virtual tour analytics"
  on public.virtual_tour_analytics_events;

create policy "Management admins read virtual tour analytics"
  on public.virtual_tour_analytics_events
  for select
  to authenticated
  using (public.is_management_admin());

create or replace function public.get_virtual_tour_analytics(
  p_tour_id uuid
)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'total_views', (
      select count(*)
      from public.virtual_tour_analytics_events event
      where event.tour_id = p_tour_id
        and event.event_type = 'tour_view'
    ),
    'views_last_30_days', (
      select count(*)
      from public.virtual_tour_analytics_events event
      where event.tour_id = p_tour_id
        and event.event_type = 'tour_view'
        and event.created_at >= now() - interval '30 days'
    ),
    'views_last_7_days', (
      select count(*)
      from public.virtual_tour_analytics_events event
      where event.tour_id = p_tour_id
        and event.event_type = 'tour_view'
        and event.created_at >= now() - interval '7 days'
    ),
    'whatsapp_clicks', (
      select count(*)
      from public.virtual_tour_analytics_events event
      where event.tour_id = p_tour_id
        and event.event_type = 'whatsapp_click'
    ),
    'embedded_views', (
      select count(*)
      from public.virtual_tour_analytics_events event
      where event.tour_id = p_tour_id
        and event.event_type = 'tour_view'
        and event.is_embedded = true
    ),
    'scene_ranking', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'scene_id', ranking.scene_id,
          'scene_name', ranking.scene_name,
          'views', ranking.views
        )
        order by ranking.views desc, ranking.scene_name asc
      )
      from (
        select
          scene.id as scene_id,
          scene.name as scene_name,
          count(event.id) as views
        from public.virtual_tour_scenes scene
        left join public.virtual_tour_analytics_events event
          on event.scene_id = scene.id
          and event.tour_id = p_tour_id
          and event.event_type = 'scene_view'
        where scene.tour_id = p_tour_id
        group by scene.id, scene.name
      ) ranking
    ), '[]'::jsonb),
    'daily_views', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'date', days.day,
          'views', coalesce(counts.views, 0)
        )
        order by days.day asc
      )
      from generate_series(
        (current_date - 13)::timestamp,
        current_date::timestamp,
        interval '1 day'
      ) as days(day)
      left join (
        select
          (event.created_at at time zone 'America/Sao_Paulo')::date as day,
          count(*) as views
        from public.virtual_tour_analytics_events event
        where event.tour_id = p_tour_id
          and event.event_type = 'tour_view'
          and event.created_at >= now() - interval '14 days'
        group by 1
      ) counts
        on counts.day = days.day::date
    ), '[]'::jsonb)
  );
$$;

revoke all on function public.get_virtual_tour_analytics(uuid)
  from public, anon, authenticated;

grant execute on function public.get_virtual_tour_analytics(uuid)
  to service_role;

comment on table public.virtual_tour_analytics_events is
  'Eventos anônimos dos passeios 360°: visualização, ambiente acessado e clique no WhatsApp.';

comment on function public.get_virtual_tour_analytics(uuid) is
  'Resumo administrativo das estatísticas de um passeio virtual 360°.';
